package com.google.codelab.gamingzone.presentation.ui.theme

import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF126B56)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFA3F2D7)
val onPrimaryContainerLight = Color(0xFF005140)
val secondaryLight = Color(0xFF076B5B)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFA0F2DD)
val onSecondaryContainerLight = Color(0xFF005144)
val tertiaryLight = Color(0xFF406376)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFC4E7FF)
val onTertiaryContainerLight = Color(0xFF284B5D)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF93000A)
val backgroundLight = Color(0xFFF5FBF6)
val onBackgroundLight = Color(0xFF171D1A)
val surfaceLight = Color(0xFFF5FBF6)
val onSurfaceLight = Color(0xFF171D1A)
val surfaceVariantLight = Color(0xFFDBE5DF)
val onSurfaceVariantLight = Color(0xFF3F4945)
val outlineLight = Color(0xFF6F7975)
val outlineVariantLight = Color(0xFFBFC9C3)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF2B322F)
val inverseOnSurfaceLight = Color(0xFFECF2EE)
val inversePrimaryLight = Color(0xFF87D6BC)
val surfaceDimLight = Color(0xFFD5DBD7)
val surfaceBrightLight = Color(0xFFF5FBF6)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFEFF5F1)
val surfaceContainerLight = Color(0xFFE9EFEB)
val surfaceContainerHighLight = Color(0xFFE4EAE5)
val surfaceContainerHighestLight = Color(0xFFDEE4E0)


val primaryDark = Color(0xFF87D6BC)
val onPrimaryDark = Color(0xFF00382B)
val primaryContainerDark = Color(0xFF005140)
val onPrimaryContainerDark = Color(0xFFA3F2D7)
val secondaryDark = Color(0xFF84D6C2)
val onSecondaryDark = Color(0xFF00382E)
val secondaryContainerDark = Color(0xFF005144)
val onSecondaryContainerDark = Color(0xFFA0F2DD)
val tertiaryDark = Color(0xFFA8CBE2)
val onTertiaryDark = Color(0xFF0D3446)
val tertiaryContainerDark = Color(0xFF284B5D)
val onTertiaryContainerDark = Color(0xFFC4E7FF)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF0F1512)
val onBackgroundDark = Color(0xFFDEE4E0)
val surfaceDark = Color(0xFF0F1512)
val onSurfaceDark = Color(0xFFDEE4E0)
val surfaceVariantDark = Color(0xFF3F4945)
val onSurfaceVariantDark = Color(0xFFBFC9C3)
val outlineDark = Color(0xFF89938E)
val outlineVariantDark = Color(0xFF3F4945)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFDEE4E0)
val inverseOnSurfaceDark = Color(0xFF2B322F)
val inversePrimaryDark = Color(0xFF126B56)
val surfaceDimDark = Color(0xFF0F1512)
val surfaceBrightDark = Color(0xFF343B38)
val surfaceContainerLowestDark = Color(0xFF090F0D)
val surfaceContainerLowDark = Color(0xFF171D1A)
val surfaceContainerDark = Color(0xFF1B211E)
val surfaceContainerHighDark = Color(0xFF252B29)
val surfaceContainerHighestDark = Color(0xFF303633)

val customBlue = Color(0xFF00DBDE)
val customPink = Color(0xFFFC00FF)

val customGreen = Color(0xFF1B5E20)
